In [71]:
import pandas as pd

In [72]:
from sqlalchemy import create_engine

In [73]:
df = pd.read_csv('/Users/lilianmaina/Desktop/Projects/DataEngineeringProject/wfp_food_prices_ken.csv')
df

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
0,2006-01-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,cereals and tubers,Maize,51,KG,actual,Wholesale,KES,16.13,0.22
1,2006-01-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,pulses and nuts,Beans,50,KG,actual,Wholesale,KES,33.63,0.47
2,2006-01-15,Eastern,Marsabit,Marsabit,190,2.33,37.98,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,21.00,0.29
3,2006-01-15,Nairobi,Nairobi,Nairobi,184,-1.28,36.82,cereals and tubers,Bread,55,400 G,actual,Retail,KES,26.00,0.36
4,2006-01-15,Nairobi,Nairobi,Nairobi,184,-1.28,36.82,cereals and tubers,Maize,51,KG,actual,Wholesale,KES,15.48,0.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17627,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,milk and dairy,Milk (UHT),794,500 ML,aggregate,Retail,KES,80.00,0.62
17628,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,miscellaneous food,Sugar,97,KG,aggregate,Retail,KES,169.72,1.31
17629,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,oil and fats,Oil (vegetable),96,L,aggregate,Retail,KES,290.28,2.24
17630,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,pulses and nuts,Beans (dry),262,KG,aggregate,Retail,KES,140.28,1.08
17631,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,vegetables and fruits,Bananas,254,Unit,aggregate,Retail,KES,20.00,0.15

In [74]:
df.shape

(17632, 16)

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17632 entries, 0 to 17631
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          17632 non-null  str
 1   admin1        17585 non-null  str
 2   admin2        17585 non-null  str
 3   market        17632 non-null  str
 4   market_id     17632 non-null  int64
 5   latitude      17585 non-null  float64
 6   longitude     17585 non-null  float64
 7   category      17632 non-null  str
 8   commodity     17632 non-null  str
 9   commodity_id  17632 non-null  int64
 10  unit          17632 non-null  str
 11  priceflag     17632 non-null  str
 12  pricetype     17632 non-null  str
 13  currency      17632 non-null  str
 14  price         17632 non-null  float64
 15  usdprice      17632 non-null  float64
dtypes: float64(4), int64(2), str(10)
memory usage: 2.2 MB

In [76]:
df.columns

Index(['date', 'admin1', 'admin2', 'market', 'market_id', 'latitude',
       'longitude', 'category', 'commodity', 'commodity_id', 'unit',
       'priceflag', 'pricetype', 'currency', 'price', 'usdprice'],
      dtype='str')

In [77]:
df.head()

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
0,2006-01-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,cereals and tubers,Maize,51,KG,actual,Wholesale,KES,16.13,0.22
1,2006-01-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,pulses and nuts,Beans,50,KG,actual,Wholesale,KES,33.63,0.47
2,2006-01-15,Eastern,Marsabit,Marsabit,190,2.33,37.98,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,21.00,0.29
3,2006-01-15,Nairobi,Nairobi,Nairobi,184,-1.28,36.82,cereals and tubers,Bread,55,400 G,actual,Retail,KES,26.00,0.36
4,2006-01-15,Nairobi,Nairobi,Nairobi,184,-1.28,36.82,cereals and tubers,Maize,51,KG,actual,Wholesale,KES,15.48,0.22

In [78]:
df.isnull().sum()

date             0
admin1          47
admin2          47
market           0
market_id        0
latitude        47
longitude       47
category         0
commodity        0
commodity_id     0
unit             0
priceflag        0
pricetype        0
currency         0
price            0
usdprice         0
dtype: int64

In [79]:
engine = create_engine('mysql+pymysql://root:Hahaha!1!@localhost:3306/food_prices_ken')

In [80]:
df.to_sql(
  name = 'raw_food_prices',
  con = engine,
  if_exists = 'append',
  index = False
)
print('Successfully added and loaded to food_prices_ken db')

Successfully added and loaded to food_prices_ken db

In [81]:
sql_query = """
SELECT date, market, commodity, unit, price, currency
FROM raw_food_prices
WHERE admin1 = 'Nairobi'
ORDER BY date DESC
LIMIT 20; """

In [82]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

         date             market         commodity   unit    price currency
0  2025-10-15  Kangemi (Nairobi)  Beans (dolichos)  90 KG   5700.0      KES
1  2025-10-15  Kangemi (Nairobi)  Beans (dolichos)  90 KG   5700.0      KES
2  2025-10-15  Kangemi (Nairobi)  Beans (rosecoco)  90 KG  10300.0      KES
3  2025-10-15  Kangemi (Nairobi)  Beans (dolichos)  90 KG   5700.0      KES
4  2025-10-15  Kangemi (Nairobi)          Tomatoes  64 KG   2880.0      KES
5  2025-10-15  Kangemi (Nairobi)          Tomatoes  64 KG   2880.0      KES
6  2025-10-15  Kangemi (Nairobi)          Tomatoes  64 KG   2880.0      KES
7  2025-10-15  Kangemi (Nairobi)  Beans (rosecoco)  90 KG  10300.0      KES
8  2025-10-15  Kangemi (Nairobi)  Beans (rosecoco)  90 KG  10300.0      KES
9  2025-10-15  Kangemi (Nairobi)  Beans (rosecoco)  90 KG  10300.0      KES
10 2025-10-15  Kangemi (Nairobi)  Beans (dolichos)  90 KG   5700.0      KES
11 2025-10-15  Kangemi (Nairobi)          Tomatoes  64 KG   2880.0      KES
12 2025-10-15  Kangemi (Nairobi)  Beans (rosecoco)  90 KG  10300.0      KES
13 2025-10-15  Kangemi (Nairobi)  Beans (dolichos)  90 KG   5700.0      KES
14 2025-10-15  Kangemi (Nairobi)  Beans (dolichos)  90 KG   5700.0      KES
15 2025-10-15  Kangemi (Nairobi)  Beans (rosecoco)  90 KG  10300.0      KES
16 2025-10-15  Kangemi (Nairobi)  Beans (dolichos)  90 KG   5700.0      KES
17 2025-10-15  Kangemi (Nairobi)          Tomatoes  64 KG   2880.0      KES
18 2025-10-15  Kangemi (Nairobi)  Beans (rosecoco)  90 KG  10300.0      KES
19 2025-10-15  Kangemi (Nairobi)          Tomatoes  64 KG   2880.0      KES

In [83]:
sql_query = """
SELECT commodity, 
	ROUND(AVG(price), 2) AS avg_price,
    MIN(price) AS min_price,
    MAX(price) AS max_price,
    COUNT(*) AS total_records
FROM raw_food_prices
GROUP BY commodity
ORDER BY avg_price DESC; """

In [84]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

                     commodity  avg_price  min_price  max_price  total_records
0               Beans (yellow)   10706.14    5400.00   18252.00           2136
1             Beans (dolichos)   10191.44    1500.00   17100.00           1280
2                 Beans (mung)    9895.15    7200.00   12270.00            264
3             Beans (rosecoco)    9440.35    5850.00   19800.00           1328
4                      Cowpeas    8604.62    2100.42   16200.00           1280
5               Beans (kidney)    7490.53    1134.00   14850.00            632
6              Millet (finger)    7396.64    3600.00   11997.00            360
7              Sorghum (white)    5900.84    2700.00    8700.00            648
8    Rice (imported, Pakistan)    4931.47    3917.00    6305.00            120
9                Sorghum (red)    4847.07    3240.00    7200.00            408
10                    Tomatoes    3776.23     426.88   10628.48           2680
11                     Cabbage    3204.52      27.46   11970.00           2552
12     Potatoes (Irish, white)    2486.15     751.00    6120.00           2224
13                     Sorghum    2458.58      30.00    7470.00           5584
14                 Beans (dry)    2415.99      23.00   10000.00           8864
15       Potatoes (Irish, red)    2346.65     868.00    5310.00           1016
16          Maize (white, dry)    2055.00      33.00    8128.00           4664
17             Rice (aromatic)    1986.30      87.00   10000.00           4840
18               Maize (white)    1104.95       8.00    4898.00           9728
19            Potatoes (Irish)    1061.69      35.00    5700.00           7312
20                        Kale     918.45       5.00    5000.00           4176
21                Onions (dry)     913.57     390.00    8100.00           2680
22                 Meat (goat)     615.20     400.00     881.25           1824
23                Meat (camel)     532.31     400.00     700.00           1184
24                 Meat (beef)     531.91      10.00     800.00           1872
25  Oil (vegetable, fortified)     292.05     120.00     403.00           3664
26             Oil (vegetable)     238.66     115.00     400.00           4496
27           Pigeon peas (dry)     214.59     100.00     700.00            528
28                 Cooking fat     188.13     120.00     380.00            712
29               Cowpeas (dry)     163.63      50.00     310.00           1200
30                       Sugar     158.67      90.36     305.00           7080
31           Fish (omena, dry)     156.69     130.00     198.00            104
32         Milk (camel, fresh)     136.08      50.00     280.00            568
33           Milk (cow, fresh)     123.96      60.00     203.89            128
34                        Rice     121.56      78.33     220.00           2832
35     Milk (cow, pasteurized)     121.01      20.00     280.00           3768
36                       Beans     105.66      28.23     270.00           8152
37      Fuel (petrol-gasoline)     102.12      83.33     118.11            352
38                 Wheat flour      98.69      50.00     174.00           6376
39         Maize flour (white)      96.13      46.00     195.00           3984
40               Fuel (diesel)      90.41      65.70     109.72            344
41                 Maize flour      81.30      50.00     137.80           3576
42                     Spinach      79.19      14.00     260.00           1472
43             Fuel (kerosene)      77.80      39.62     111.83            280
44                  Milk (UHT)      70.38      27.00     100.45           3296
45                       Bread      40.18      26.00      50.00            848
46                       Maize      39.29      10.43     120.00           8288
47               Cowpea leaves      32.02      10.00      87.00            216
48                     Bananas      14.19       5.00      21.67           2688
49                        Salt      12.19       8.24      55.00           6448

In [85]:
sql_query = """
SELECT commodity, COUNT(DISTINCT market) AS market_count -- REVIEW WITHOUT DISTINCT
FROM raw_food_prices
GROUP BY commodity
HAVING market_count > 10
ORDER BY market_count DESC;
"""

In [86]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

                     commodity  market_count
0                        Sugar           186
1              Rice (aromatic)           181
2                  Wheat flour           176
3                         Salt           173
4                        Beans           172
5          Maize flour (white)           170
6   Oil (vegetable, fortified)           161
7           Maize (white, dry)           155
8      Milk (cow, pasteurized)           153
9                         Kale           125
10                     Spinach            97
11               Cowpeas (dry)            85
12           Pigeon peas (dry)            48
13                 Beans (dry)            40
14            Potatoes (Irish)            37
15                     Cabbage            35
16                       Maize            35
17                 Maize flour            32
18                     Bananas            32
19                  Milk (UHT)            32
20                        Rice            32
21             Oil (vegetable)            31
22                     Sorghum            31
23                 Meat (beef)            28
24                 Meat (goat)            23
25                 Cooking fat            23
26                Onions (dry)            21
27                    Tomatoes            21
28              Beans (yellow)            19
29         Milk (camel, fresh)            19
30                Meat (camel)            17
31                     Cowpeas            17
32       Potatoes (Irish, red)            17
33     Potatoes (Irish, white)            17
34            Beans (rosecoco)            17
35              Beans (kidney)            17
36            Beans (dolichos)            16
37               Maize (white)            14
38               Sorghum (red)            14
39             Sorghum (white)            13
40             Millet (finger)            12
41                Beans (mung)            12
42           Milk (cow, fresh)            11

In [87]:
sql_query = """
SELECT admin2, EXTRACT(YEAR FROM date) AS year, ROUND(AVG(price), 2) as avg_price
FROM raw_food_prices
GROUP BY admin2, year
ORDER BY admin2, year;
"""

In [88]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

         admin2  year  avg_price
0           NaN  2015      38.50
1           NaN  2016      46.75
2           NaN  2017      60.76
3           NaN  2018      53.41
4           NaN  2019      56.26
..          ...   ...        ...
253       Wajir  2024     139.33
254       Wajir  2025     146.33
255  West Pokot  2021    4595.51
256  West Pokot  2022    4399.39
257  West Pokot  2023    5198.17

[258 rows x 3 columns]

In [89]:
sql_query = """
SELECT date, admin2, market, commodity, price
FROM raw_food_prices
WHERE date >= '2025-01-01'
ORDER BY date DESC;
"""

In [90]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

,date,admin2,market,commodity,price
0,2025-11-15,Kisumu,Kibuye (Kisumu),"Potatoes (Irish, white)",4300.00
1,2025-11-15,Garissa,Dagahaley (Daadab),Maize flour,99.22
2,2025-11-15,Garissa,Dagahaley (Daadab),Potatoes (Irish),60.16
3,2025-11-15,Garissa,Dagahaley (Daadab),Wheat flour,99.65
4,2025-11-15,Garissa,Dagahaley (Daadab),Meat (goat),881.25
...,...,...,...,...,...
11755,2025-01-15,Nairobi,Kangemi (Nairobi),Cowpeas,9666.90
11756,2025-01-15,Nairobi,Kangemi (Nairobi),Tomatoes,5120.00
11757,2025-01-15,Kisumu,Kibuye (Kisumu),"Maize (white, dry)",4416.30
11758,2025-01-15,Kisumu,Kibuye (Kisumu),"Potatoes (Irish, white)",4000.00
11759,2025-01-15,Kisumu,Kibuye (Kisumu),Kale,1441.00

In [91]:
sql_query = """
SELECT commodity, pricetype, ROUND(AVG(price), 2) AS avg_price, COUNT(*) AS records
FROM raw_food_prices
GROUP BY commodity, pricetype
ORDER BY commodity, pricetype
"""

In [92]:
df_all = pd.read_sql(sql_query, con=engine)
df_all

           commodity  pricetype  avg_price  records
0            Bananas     Retail      14.19     2688
1              Beans     Retail     159.68     3704
2              Beans  Wholesale      60.68     4448
3   Beans (dolichos)  Wholesale   10191.44     1280
4        Beans (dry)     Retail     113.91     5312
..               ...        ...        ...      ...
56           Spinach     Retail      92.14     1168
57           Spinach  Wholesale      29.42      304
58             Sugar     Retail     158.67     7080
59          Tomatoes  Wholesale    3776.23     2680
60       Wheat flour     Retail      98.69     6376

[61 rows x 4 columns]

In [93]:
df[df['admin1'].isnull()]

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
2393,2015-01-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,35.00,0.38
2421,2015-02-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,35.00,0.38
2548,2015-06-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,36.00,0.37
2580,2015-07-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,42.00,0.41
2615,2015-08-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,41.00,0.40
2643,2015-09-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,39.25,0.37
2678,2015-10-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,31.25,0.30
2709,2015-11-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,44.47,0.43
2734,2015-12-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,42.50,0.42
2766,2016-01-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,39.17,0.38
2798,2016-02-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,39.38,0.39
2836,2016-03-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,38.35,0.38
2880,2016-05-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,41.67,0.41
2976,2016-08-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,53.45,0.53
3009,2016-09-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,54.00,0.53
3041,2016-10-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,58.00,0.57
3102,2016-12-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,50.00,0.49
3131,2017-01-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,53.20,0.51
3200,2017-03-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,57.30,0.56
3270,2017-05-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,60.00,0.58
3301,2017-06-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,80.00,0.78
3390,2017-09-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,64.00,0.62
3427,2017-10-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,60.00,0.58
3460,2017-11-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,50.83,0.49
3525,2018-01-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,55.00,0.53
3550,2018-02-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,55.00,0.54
3584,2018-03-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,58.00,0.57
3622,2018-04-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,50.00,0.50
3690,2018-06-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,57.00,0.56
3724,2018-07-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,55.00,0.55
3825,2018-10-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,55.30,0.55
3893,2018-12-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,42.00,0.41
3932,2019-01-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,63.00,0.62
3967,2019-02-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,64.00,0.64
4004,2019-03-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,54.00,0.54
4040,2019-04-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,51.00,0.51
4143,2019-07-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,59.30,0.58
4177,2019-08-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,56.80,0.55
4198,2019-09-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,52.20,0.50
4231,2019-10-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,40.00,0.39
4281,2019-12-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,66.00,0.65
4381,2020-05-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,66.00,0.62
4398,2020-06-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,57.00,0.53
4417,2020-07-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,57.00,0.53
4436,2020-08-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,66.00,0.61
4457,2020-09-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,55.00,0.51
4465,2020-10-15,NaN,NaN,Hola (Tana River),1854,NaN,NaN,cereals and tubers,Maize (white),67,KG,actual,Retail,KES,53.00,0.49

In [94]:
df[df['admin1'].isnull()]['market'].unique()

<StringArray>
['Hola (Tana River)']
Length: 1, dtype: str

In [95]:
df.loc[df['market'] == 'Hola (Tana River)', 'admin1'] = 'Tana River'
df.loc[df['market'] == 'Hola (Tana River)', 'admin2'] = 'Tana River'
df.loc[df['market'] == 'Hola (Tana River)', 'latitude'] = -1.0
df.loc[df['market'] == 'Hola (Tana River)', 'longitude'] = 40.0

In [96]:
df[df['market'] == 'Hola (Tana River)'].isnull().sum()

date            0
admin1          0
admin2          0
market          0
market_id       0
latitude        0
longitude       0
category        0
commodity       0
commodity_id    0
unit            0
priceflag       0
pricetype       0
currency        0
price           0
usdprice        0
dtype: int64

In [97]:
df['pricetype'].unique()

<StringArray>
['Wholesale', 'Retail']
Length: 2, dtype: str

In [98]:
df['date'].head()

0    2006-01-15
1    2006-01-15
2    2006-01-15
3    2006-01-15
4    2006-01-15
Name: date, dtype: str

In [99]:
df['date'] = pd.to_datetime(df['date'])

In [100]:
df['date'].head()

0   2006-01-15
1   2006-01-15
2   2006-01-15
3   2006-01-15
4   2006-01-15
Name: date, dtype: datetime64[us]

In [101]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

In [102]:
df[['date', 'year', 'month']].tail()

            date  year  month
17627 2025-11-15  2025     11
17628 2025-11-15  2025     11
17629 2025-11-15  2025     11
17630 2025-11-15  2025     11
17631 2025-11-15  2025     11

In [103]:
df['unit'].unique()

<StringArray>
[    'KG',  '400 G',  '90 KG',  '50 KG', '500 ML',      'L', '200 ML',
   'Unit',  'Bunch', '126 KG',  '13 KG',  '64 KG',  '200 G',   'Head']
Length: 14, dtype: str

In [104]:
df[df['commodity_id'] == 50]

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice,year,month
1,2006-01-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,pulses and nuts,Beans,50,KG,actual,Wholesale,KES,33.63,0.47,2006,1
10,2006-01-15,Nairobi,Nairobi,Nairobi,184,-1.28,36.82,pulses and nuts,Beans,50,KG,actual,Wholesale,KES,42.31,0.59,2006,1
15,2006-01-15,Nyanza,Kisumu,Kisumu,186,-0.10,34.75,pulses and nuts,Beans,50,KG,actual,Wholesale,KES,39.61,0.55,2006,1
20,2006-01-15,Rift Valley,Uasin Gishu,Eldoret town (Uasin Gishu),185,0.52,35.28,pulses and nuts,Beans,50,KG,actual,Wholesale,KES,45.85,0.64,2006,1
22,2006-02-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,pulses and nuts,Beans,50,KG,actual,Wholesale,KES,39.48,0.55,2006,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11978,2025-09-15,Rift Valley,Turkana,Katilia,6898,2.14,36.14,pulses and nuts,Beans,50,KG,actual,Retail,KES,164.00,1.27,2025,9
11986,2025-09-15,Rift Valley,Turkana,Kibish,6904,4.57,35.31,pulses and nuts,Beans,50,KG,actual,Retail,KES,141.00,1.09,2025,9
11991,2025-09-15,Rift Valley,Turkana,Letea,6903,3.52,35.75,pulses and nuts,Beans,50,KG,actual,Retail,KES,120.00,0.93,2025,9
11999,2025-09-15,Rift Valley,Turkana,Lokori,6897,1.95,36.03,pulses and nuts,Beans,50,KG,actual,Retail,KES,151.00,1.17,2025,9
12003,2025-09-15,Rift Valley,Turkana,Lorugum,6894,2.88,35.25,pulses and nuts,Beans,50,KG,actual,Retail,KES,150.00,1.16,2025,9

In [105]:
df['unit'] = df['unit'].apply(lambda x: '1 ' + x if ' ' not in x else x)

In [106]:
df['quantity'] = df['unit'].apply(lambda x: float(x.split(' ')[0]) if ' ' in x else 1)

In [107]:
df['unit_type'] = df['unit'].apply(lambda x: x.split(' ')[1] if ' ' in x else x)

In [108]:
df['price_per_unit'] = df['price'] / df['quantity']

In [109]:
df.drop(columns = ['unit'], inplace = True)

In [110]:
df

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,priceflag,pricetype,currency,price,usdprice,year,month,quantity,unit_type,price_per_unit
0,2006-01-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,cereals and tubers,Maize,51,actual,Wholesale,KES,16.13,0.22,2006,1,1.0,KG,16.130
1,2006-01-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,pulses and nuts,Beans,50,actual,Wholesale,KES,33.63,0.47,2006,1,1.0,KG,33.630
2,2006-01-15,Eastern,Marsabit,Marsabit,190,2.33,37.98,cereals and tubers,Maize (white),67,actual,Retail,KES,21.00,0.29,2006,1,1.0,KG,21.000
3,2006-01-15,Nairobi,Nairobi,Nairobi,184,-1.28,36.82,cereals and tubers,Bread,55,actual,Retail,KES,26.00,0.36,2006,1,400.0,G,0.065
4,2006-01-15,Nairobi,Nairobi,Nairobi,184,-1.28,36.82,cereals and tubers,Maize,51,actual,Wholesale,KES,15.48,0.22,2006,1,1.0,KG,15.480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17627,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,milk and dairy,Milk (UHT),794,aggregate,Retail,KES,80.00,0.62,2025,11,500.0,ML,0.160
17628,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,miscellaneous food,Sugar,97,aggregate,Retail,KES,169.72,1.31,2025,11,1.0,KG,169.720
17629,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,oil and fats,Oil (vegetable),96,aggregate,Retail,KES,290.28,2.24,2025,11,1.0,L,290.280
17630,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,pulses and nuts,Beans (dry),262,aggregate,Retail,KES,140.28,1.08,2025,11,1.0,KG,140.280
17631,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,vegetables and fruits,Bananas,254,aggregate,Retail,KES,20.00,0.15,2025,11,1.0,Unit,20.000

In [111]:
df['quantity'] = df['quantity'].astype(int)

In [112]:
df['price_per_unit'] = df['price_per_unit'].round(2)

In [113]:
df

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,priceflag,pricetype,currency,price,usdprice,year,month,quantity,unit_type,price_per_unit
0,2006-01-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,cereals and tubers,Maize,51,actual,Wholesale,KES,16.13,0.22,2006,1,1,KG,16.13
1,2006-01-15,Coast,Mombasa,Mombasa,191,-4.05,39.67,pulses and nuts,Beans,50,actual,Wholesale,KES,33.63,0.47,2006,1,1,KG,33.63
2,2006-01-15,Eastern,Marsabit,Marsabit,190,2.33,37.98,cereals and tubers,Maize (white),67,actual,Retail,KES,21.00,0.29,2006,1,1,KG,21.00
3,2006-01-15,Nairobi,Nairobi,Nairobi,184,-1.28,36.82,cereals and tubers,Bread,55,actual,Retail,KES,26.00,0.36,2006,1,400,G,0.06
4,2006-01-15,Nairobi,Nairobi,Nairobi,184,-1.28,36.82,cereals and tubers,Maize,51,actual,Wholesale,KES,15.48,0.22,2006,1,1,KG,15.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17627,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,milk and dairy,Milk (UHT),794,aggregate,Retail,KES,80.00,0.62,2025,11,500,ML,0.16
17628,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,miscellaneous food,Sugar,97,aggregate,Retail,KES,169.72,1.31,2025,11,1,KG,169.72
17629,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,oil and fats,Oil (vegetable),96,aggregate,Retail,KES,290.28,2.24,2025,11,1,L,290.28
17630,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,pulses and nuts,Beans (dry),262,aggregate,Retail,KES,140.28,1.08,2025,11,1,KG,140.28
17631,2025-11-15,Rift Valley,Turkana,Mogadishu (Kakuma),3245,3.72,34.85,vegetables and fruits,Bananas,254,aggregate,Retail,KES,20.00,0.15,2025,11,1,Unit,20.00

In [117]:
df['latitude'].unique()

array([-4.05,  2.33, -1.28,  3.94, -0.1 ,  3.12,  0.52, -1.37, -0.28,
       -1.  , -3.63, -0.46,  0.46, -1.84, -0.48, -4.66, -1.36, -1.81,
       -1.79, -1.29,  3.39,  0.47, -2.1 , -0.3 ,  1.44, -4.06, -1.27,
        1.25, -1.91, -0.32, -0.09, -4.04, -0.72, -0.34, -1.19, -0.78,
       -2.27, -1.5 , -1.33, -0.14, -2.44, -1.53,  0.5 ,  0.9 ,  0.57,
        0.96,  0.53,  0.99,  0.6 ,  1.27,  0.84,  1.07,  0.73,  0.62,
        1.13,  2.29,  2.21,  2.49,  2.1 ,  2.01,  1.58,  1.99,  2.76,
        1.42,  2.25,  0.19,  0.28,  0.01,  0.11,  0.38,  3.55,  3.92,
        3.93,  3.36,  2.  ,  0.36,  0.95,  1.65,  0.88,  1.78,  0.87,
        1.06,  1.08,  1.02,  0.89,  1.1 ,  1.15,  1.74,  1.22,  0.83,
        0.98,  3.53,  4.06,  4.52,  3.98,  3.74,  2.14,  2.74,  4.37,
        3.77,  3.76,  3.75,  3.54,  4.62,  3.52,  2.38,  4.2 ,  4.27,
        1.95,  3.86,  2.88,  2.93,  4.28,  2.54,  3.51,  4.58,  2.2 ,
        2.84,  4.56,  2.92,  2.95, -2.69, -1.01, -2.53, -2.08, -2.41,
        0.44, -0.03,  0.65,  0.06,  0.1 , -0.04,  0.35, -0.85,  2.81,
        1.53,  1.29,  0.77,  3.24,  4.1 ,  2.37,  1.98,  2.02,  3.72,
       -0.47, -1.7 , -2.32, -1.61,  0.32,  3.32,  3.45,  0.16, -1.85,
       -1.97,  3.05,  3.41,  2.79,  0.64,  1.61,  1.8 ,  2.11,  3.71,
        2.48,  4.57,  2.58,  4.44, -3.25, -3.48, -3.33,  3.56, -0.61,
        3.15,  2.15,  3.18, -3.4 , -4.01, -4.03, -4.11, -1.32, -1.26,
       -1.3 , -1.25,  1.75])

In [115]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17632 entries, 0 to 17631
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            17632 non-null  datetime64[us]
 1   admin1          17632 non-null  str
 2   admin2          17632 non-null  str
 3   market          17632 non-null  str
 4   market_id       17632 non-null  int64
 5   latitude        17632 non-null  float64
 6   longitude       17632 non-null  float64
 7   category        17632 non-null  str
 8   commodity       17632 non-null  str
 9   commodity_id    17632 non-null  int64
 10  priceflag       17632 non-null  str
 11  pricetype       17632 non-null  str
 12  currency        17632 non-null  str
 13  price           17632 non-null  float64
 14  usdprice        17632 non-null  float64
 15  year            17632 non-null  int32
 16  month           17632 non-null  int32
 17  quantity        17632 non-null  int64
 18  unit_type       17632 non-null  str
 19  price_per_unit  17632 non-null  float64
dtypes: datetime64[us](1), float64(5), int32(2), int64(3), str(9)
memory usage: 2.6 MB

In [118]:
df.to_sql(
  name = 'staging_food_prices',
  con = engine,
  if_exists = 'append',
  index = False
)
print('Successfully added and loaded to food_prices_ken db')

Successfully added and loaded to food_prices_ken db